project_version=2.8.0-dev.1

# FM Protocols
compat_layer_version=1e9f6470d7
protocols_version=5f6a89f3f0
protocols_use_local_build=false
protocols_local_version=2.3.6

mc_version=1.21.11
minecraft_version=1.21.11-R0.1-SNAPSHOT

# Dependencies
packetevents_use_local_build=false
packetevents_version=2.11.0
#protocollib_version=5.3.0
#ld_version=10.0.33
pluginbase_version=504fa9e348
gsit_version=1.6.0
papi_version=2.11.5
bstats_version=3.0.2
me_version = R4.0.4
towny_version = 0.100.4.0