project_version=2.1.0.beta6

# FM Protocols
compat_layer_version=2e128d96ff
protocols_version=5cdc0ca682
protocols_use_local_build=false
protocols_local_version=2.1.1

mc_version=1.21.5
minecraft_version=1.21.5-no-moonrise-SNAPSHOT

# Dependencies
packetevents_version=2.8.0
#protocollib_version=5.3.0
#ld_version=10.0.33
pluginbase_version=f88301fa8f
gsit_version=1.6.0
papi_version=2.11.5
bstats_version=3.0.2
me_version = R4.0.4
towny_version = 0.100.4.0