project_version=2.5.0-SNAPSHOT

# FM Protocols
compat_layer_version=501c1f2396
protocols_version=12b6d2f12b
protocols_use_local_build=false
protocols_local_version=2.3.6

mc_version=1.21.9
minecraft_version=1.21.9-rc1-R0.1-SNAPSHOT

# Dependencies
packetevents_version=2.9.6-SNAPSHOT
#protocollib_version=5.3.0
#ld_version=10.0.33
pluginbase_version=f88301fa8f
gsit_version=1.6.0
papi_version=2.11.5
bstats_version=3.0.2
me_version = R4.0.4
towny_version = 0.100.4.0