/*
 * This file was generated by the Gradle 'init' task.
 */
pluginManagement {
}

plugins {

    // See https://github.com/jpenilla/run-task/wiki/Debugging#hot-swap
    // add toolchain resolver
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.9.0"
}

rootProject.name = "feathermorph"
include("command-compat-layer")
